# Use postgres/example user/password credentials
services:
  web:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    ports: 
      - 4004:4004
    command: [
      "sh",
      "-c",
      "mix deps.get && mix phx.server"
    ]
    environment:
      MIX_ENV: dev